### ISSUE TITLE
I cann't fine argv file in this file.

### ISSUE THREAD

**Issue by bnkim1014** [silverneko/Linear-RNN#2]
Hellow, I'm trying to do your code.
But, I have some problem that there is compile error in test-denoise.py which is about "argv"
In your project code, I can not find a agrv file or code.

Please help me.

**Comment by silverneko** [comment]
`argv` is a symbol imported from the `sys` package: https://github.com/silverneko/Linear-RNN/blob/master/test-denoise.py#L8
